runtime: python31013

entrypoint: uvicorn main:app --host=127.0.0.1: --port=8000

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  MODEL_PATH: 'mri-model.h5'

# Optional: Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# Optional: Health check configuration
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2